### ISSUE TITLE
Why not depend on native (puppetlabs) modules ?

### ISSUE THREAD

**Issue by Yamakasi** [Puppet-Finland/librenms#1]
Hi guys,

I think I love your module but I wonder why you don't rely on the default puppet modules like stdlib, systemd, etc instead of your own. This makes it pretty difficult for other modules to use these libs from other providers, like puppetlabs, as well.

Please let me know!

Cheers,

**Comment by mattock** [comment]
We don't (actively) use LibreNMS anymore, so this module has been in a semi-abandoned state for a while.

That said, I think it would make sense to port this module to use more common dependencies such as:
* [puppetlabs/mysql](https://forge.puppet.com/puppetlabs/mysql)
* [puppetlabs/apache](https://forge.puppet.com/puppetlabs/apache)
* [puppet/php](https://forge.puppet.com/puppet/php)
* [camptocamp/systemd](https://forge.puppet.com/camptocamp/systemd)

If you are willing to do the porting I'm all for it. I can help by testing the new code on our LibreNMS instance. Once this is done I would not mind handing over the maintenance of the module to you :smile:.

**Comment by mattock** [comment]
Well, we use LibreNMS quite actively again. And in fact, we use more "standard" modules now - check the Puppetfile for example.
